# Generated by Django 3.0.4 on 2020-04-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200407_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='num_stars',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
