# Generated by Django 3.0.4 on 2020-04-25 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20200424_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='album',
            new_name='songs',
        ),
        migrations.AddField(
            model_name='album',
            name='songs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.Song'),
        ),
    ]
